      SUBROUTINE FACTOR(N)
C  FACTOR DETERMINES THE SMALLEST EVEN NUMBER .GE. N THAT CAN BE FACTORED INTO
C  PRODUCTS OF PRIMES IN THE ARRAY NP. THE RESULT IS RETURNED AS N.
C  ONLY THE FIRST FOUR PRIMES ARE USED. THIS ROUTINE IS CALLED BEFORE USING FFTL.  
      DIMENSION NP(4)
      DATA NP/2,3,5,7/
      NCHK=N/2
      IF(N.NE.(NCHK*2)) N=N+1
    5 NF=N
      DO 15 I=1,4
      M=NP(I)
   10 L=MOD(NF,M)
      IF(L.NE.0) GO TO 15
      NF=NF/M
      GO TO 10
   15 CONTINUE
      IF(NF.EQ.1) RETURN
      N=N+2
      GO TO 5
      END
