      SUBROUTINE FFTLDP(X,N,NDIR,DT,IERR)
C  FFTLDP IS A DOUBLE PRECISION VERSION OF FFTL. SEE NOTES TO FFTL FOR USAGE
C  THE SCALING IN FFTLDP DIFFERS FROM THAT IN FFTL :
C  THE FORWARD TRANSFORM IS SPECTRUM(W)=DT*SUM(0,N-1)X(J)*EXP(-I*W*J*DT)
C  THE SPACING IN W IS 2*PI/(N*DT)
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION X(1)
      N2=N/2
      IDIR=NDIR
      IF(IDIR.LT.0) IDIR=-IDIR
      GO TO (1,2),IDIR
C   DO FORWARD TRANSFORM (IE. TIME TO FREQUENCY).
 1    CALL FFTDP(X,X(2),N2,N2,N2,2,IERR)
      CALL RLTRDP(X,X(2),N2,2)
      N1=2*N2+2
      SCALE=0.5D0*DT
      IF(NDIR.GT.0) GO TO 3
      DO 5 I=4,N,2
 5    X(I)=-X(I)
      GO TO 3
C   DO BACKWARD TRANSFORM (IE. FREQUENCY TO TIME).
 2    IF(NDIR.GT.0) GO TO 6
      DO 7 I=4,N,2
 7    X(I)=-X(I)
 6    X(2)=0.D0
      N1=2*N2
      X(N1+2)=0.D0
      CALL RLTRDP(X,X(2),N2,-2)
      CALL FFTDP(X,X(2),N2,N2,N2,-2,IERR)
      SCALE=1.D0/(N*DT)
C   NORMALIZE THE TRANSFORM.
 3    DO 4 I=1,N1
 4    X(I)=SCALE*X(I)
      RETURN
      END
